//PROBLEM 2
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include<iostream>

int evenfibonaccinumbers(int until) {
	// fibonacci parity goes (starting from 1 2) like O E O O E O O E O O E O O E etc.
	// so the even terms occur at predictable indices (3n+1 for n \in \mathbb{N}_0) 
	int a = 1, b = 2, t = 0, sum = 0;
	while (b < until) {
		sum += b; // b is guaranteed even by position in seq, a term like F_{3n+1}
		a += b; // a goes from F_{3n} to F_{3n+2}
		t = a; // store F_{3n+2} in t
		a += b; // a goes from F_{3n+2} to F_{3n+3}, the odd before the next even.
		b = a + t; // b set to F_{3n+3} + F_{3n+2} = F_{3n+4}, the next even.
	}

	return sum;
}

int main() {
	std::cout << "Problem 2\n---------------\nAnswer: " << evenfibonaccinumbers(4000000) << "\n"; 
	return 0;
}
